upgrade docker to 20.10.18 from openwrt

diff --git a/utils/dockerd/files/dockerd.init b/utils/dockerd/files/dockerd.init
--- a/utils/dockerd/files/dockerd.init
+++ b/utils/dockerd/files/dockerd.init
@@ -48,8 +48,6 @@ uciadd() {
 	local iface="${1}"
 	local device="${2}"
 	local zone="${3}"
-	local netchange="false"
-	local fwchange="false"
 
 	[ -z "${iface}" ] && {
 		iface="docker"
@@ -71,7 +69,17 @@ uciadd() {
 		uci_quiet set network.@interface[-1].proto="none"
 		uci_quiet set network.@interface[-1].auto="0"
 		uci_quiet commit network
-		netchange="true"
+	fi
+
+	# Add docker bridge device
+	if [ "$(find_network_device "$device")" = "" ]; then
+		logger -t "dockerd-init" -p notice "Adding bridge device '${device}' to network config"
+		uci_quiet add network device
+		uci_quiet set network.@device[-1].type="bridge"
+		uci_quiet set network.@device[-1].name="${device}"
+		uci_quiet commit network
+	else
+		logger -t "dockerd-init" -p notice "Bridge device '${device}' already defined in network config"
 	fi
 
 	# Add firewall zone
@@ -79,27 +87,21 @@ uciadd() {
 		logger -t "dockerd-init" -p notice "Adding firewall zone '${zone}' to firewall config"
 		uci_quiet add firewall zone
 		uci_quiet rename firewall.@zone[-1]="${zone}"
-		uci_quiet set firewall.@zone[-1].name="${zone}"
 		uci_quiet set firewall.@zone[-1].input="ACCEPT"
 		uci_quiet set firewall.@zone[-1].output="ACCEPT"
 		uci_quiet set firewall.@zone[-1].forward="ACCEPT"
-		uci_quiet set firewall.@zone[-1].auto_helper="0"
+		uci_quiet set firewall.@zone[-1].name="${zone}"
 		uci_quiet commit firewall
-		fwchange="true"
 	fi
 
 	# Add interface to firewall zone
-	if ! uci -q get firewall.${zone}.network | grep -qFw "${iface}"; then
+	if uci_quiet get firewall.${zone}; then
+		uci_quiet del_list firewall.${zone}.network="${iface}"
 		uci_quiet add_list firewall.${zone}.network="${iface}"
 		uci_quiet commit firewall
-		fwchange="true"
 	fi
 
-	if $netchange ; then
-		/etc/init.d/network reload
-	elif $fwchange ; then
-		/etc/init.d/firewall reload
-	fi
+	reload_config
 }
 
 ucidel() {
@@ -173,6 +175,7 @@ process_config() {
 
 	# Don't add these options by default
 	# omission == docker defaults
+	config_get log_driver globals log_driver ""
 	config_get bip globals bip ""
 	config_get registry_mirrors globals registry_mirrors ""
 	config_get hosts globals hosts ""
@@ -181,13 +184,13 @@ process_config() {
 	config_get ip globals ip ""
 	config_get fixed_cidr globals fixed_cidr ""
 	config_get fixed_cidr_v6 globals fixed_cidr_v6 ""
-	config_get max_concurrent_downloads globals max_concurrent_downloads ""
 
 	. /usr/share/libubox/jshn.sh
 	json_init
 	json_add_string "data-root" "${data_root}"
 	json_add_string "log-level" "${log_level}"
 	json_add_boolean "iptables" "${iptables}"
+	[ -z "${log_driver}" ] || json_add_string "log-driver" "${log_driver}"
 	[ -z "${bip}" ] || json_add_string "bip" "${bip}"
 	[ -z "${registry_mirrors}" ] || json_add_array "registry-mirrors"
 	[ -z "${registry_mirrors}" ] || config_list_foreach globals registry_mirrors json_add_array_string
@@ -202,47 +205,9 @@ process_config() {
 	[ -z "${ip}" ] || json_add_string "ip" "${ip}"
 	[ -z "${fixed_cidr}" ] || json_add_string "fixed-cidr" "${fixed_cidr}"
 	[ -z "${fixed_cidr_v6}" ] || json_add_string "fixed-cidr-v6" "${fixed_cidr_v6}"
-	[ "${max_concurrent_downloads:-0}" -eq "0" ] || json_add_int "max-concurrent-downloads" "${max_concurrent_downloads}"
-	json_add_string "log-driver" "json-file"
-	json_add_object "log-opts"
-	json_add_string "max-size" "50m"
-	json_add_string "max-file" "2"
-	json_close_object
 	json_dump > "${DOCKERD_CONF}"
 
-	if [ "${iptables}" -eq "1" ]; then
-		iptables_refresh
-	fi
-}
-
-process_config_hotplug() {
-	local alt_config_file iptables
-	[ -f /etc/config/dockerd ] || {
-		return 0
-	}
-
-	config_load 'dockerd'
-	config_get alt_config_file globals alt_config_file
-	[ -n "${alt_config_file}" ] && [ -f "${alt_config_file}" ] && {
-		return 0
-	}
-	config_get_bool iptables globals iptables "1"
-	if [ "${iptables}" -eq "1" ]; then
-		iptables_refresh
-	fi
-}
-
-iptables_refresh() {
-	# Wait for a maximum of 10 second per command, retrying every millisecond
-	iptables_wait_args="--wait 10 --wait-interval 1000"
-
-	iptables ${iptables_wait_args} --table filter --new DOCKER-BLOCKED 2>/dev/null
-	[ -z "$DEVICE" ] && iptables ${iptables_wait_args} --table filter --flush DOCKER-BLOCKED
-	. /lib/functions/network.sh
-	config_foreach iptables_add_blocking_rule firewall
-	if ! iptables ${iptables_wait_args} --table filter --check DOCKER-USER --jump DOCKER-BLOCKED 2>/dev/null; then
-		iptables ${iptables_wait_args} --table filter --insert DOCKER-USER --jump DOCKER-BLOCKED
-	fi
+	[ "${iptables}" -eq "1" ] && config_foreach iptables_add_blocking_rule firewall
 }
 
 start_service() {
@@ -258,23 +223,10 @@ start_service() {
 		procd_set_param command /usr/bin/dockerd --config-file="${DOCKERD_CONF}"
 	fi
 	procd_set_param limits nofile="${nofile} ${nofile}"
-	procd_set_param respawn
 	procd_close_instance
 }
 
 reload_service() {
-	if [ -n "$DEVICE" ]; then
-		process_config_hotplug
-		return 0
-	fi
-	if [ -f "${DOCKERD_CONF}" -a -f /etc/config/dockerd ]; then
-		local oldroot=`jsonfilter -i "${DOCKERD_CONF}" -e @[\"data-root\"]`
-		local newroot=`uci get dockerd.globals.data_root`
-		if [ "$oldroot" != "$newroot" ]; then
-			restart
-			return 0
-		fi
-	fi
 	process_config
 	procd_send_signal dockerd
 }
@@ -296,20 +248,22 @@ iptables_add_blocking_rule() {
 
 		local inbound=""
 
-		network_get_device inbound "${interface}"
-
-		[ -n "$DEVICE" -a "$DEVICE" != "${inbound}" ] && return
+		. /lib/functions/network.sh
+		network_get_physdev inbound "${interface}"
 
 		[ -z "${inbound}" ] && {
 			logger -t "dockerd-init" -p notice "Unable to get physical device for interface ${interface}"
 			return
 		}
 
+		# Wait for a maximum of 10 second per command, retrying every millisecond
+		local iptables_wait_args="--wait 10 --wait-interval 1000"
+
 		# Ignore errors as it might already be present
-		iptables ${iptables_wait_args} --table filter --new DOCKER-BLOCKED 2>/dev/null
-		if ! iptables ${iptables_wait_args} --table filter --check DOCKER-BLOCKED --in-interface "${inbound}" --out-interface "${outbound}" ${extra_iptables_args} --jump REJECT 2>/dev/null; then
+		iptables ${iptables_wait_args} --table filter --new DOCKER-USER 2>/dev/null
+		if ! iptables ${iptables_wait_args} --table filter --check DOCKER-USER --in-interface "${inbound}" --out-interface "${outbound}" ${extra_iptables_args} --jump REJECT 2>/dev/null; then
 			logger -t "dockerd-init" -p notice "Drop traffic from ${inbound} to ${outbound}"
-			iptables ${iptables_wait_args} --table filter --insert DOCKER-BLOCKED --in-interface "${inbound}" --out-interface "${outbound}" ${extra_iptables_args} --jump REJECT
+			iptables ${iptables_wait_args} --table filter --insert DOCKER-USER --in-interface "${inbound}" --out-interface "${outbound}" ${extra_iptables_args} --jump REJECT
 		fi
 	}
 
